### 1.	Python program to print all negative numbers in a range

In [2]:
upper_limit=10
lower_limit=-50
a= [i for i in range(lower_limit,upper_limit) if i<0]
print(a)

[-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]


### 2.	Remove multiple elements from a list in Python

In [5]:
arr2=[1,2,3,4,5,6,7,8,9,0,10]
del arr2[::2]   #removing every 2nd element from entire list
print(arr2)

[2, 4, 6, 8, 0]


### 3.	write a Python program to Remove empty List from List

In [26]:
arr3=[1,2,3,4,[],[1,2,3],5,6,7,8,9,[],10]
r=[i for i in arr3 if i]
print(r)

[1, 2, 3, 4, [1, 2, 3], 5, 6, 7, 8, 9, 10]


### 4.	write a Python program to Cloning or Copying a list 

In [17]:
arr4=[1,2,3,4,5,6,7,8,9,[],10]
arr4_c=arr4.copy()
arr4_c

[1, 2, 3, 4, 5, 6, 7, 8, 9, [], 10]

### 5.	write a Python program to Count occurrences of an element in a list 

In [18]:
arr5=[1,2,2,4,5,6,1,8,9,5,10]
d={}
for i in arr5:
    if i not in d:
        d[i]=1
    else:
        d[i]+=1
print(d)

{1: 2, 2: 2, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 10: 1}


### 6.	write a Python program to Remove empty tuples from a list 

In [24]:
L = [(), (), ('',), ('a', 'b'), ('a', 'b', 'c'), ('d')]
L = [t for t in L if t]
print(L)

[('',), ('a', 'b'), ('a', 'b', 'c'), 'd']


### 7.	write a Python program to Program to print duplicates from a list of integers 

In [20]:
arr7=[1,2,2,4,5,6,1,8,9,5,10]
r=[]
for i in range(len(arr7)-1):
    if  arr7[i] in arr7[i+1:]:
        r.append(arr7[i])
print(r)

[1, 2, 5]


### 8.	write a Python program to find Cumulative sum of a list 

In [21]:
arr8=[1,2,3,4,5,6,7,8,9,10]
r=[]
c=0
for i in range(len(arr8)):
    c+=arr8[i]
    r.append(c)
print(r)

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


### 9.	write a Python program to Sum of number digits in List 

In [22]:
arr9=[41,52,83,94,5,26,47,78,89,10]
r=[]
for i in arr9:
    sum=0
    for j in str(i):
        sum+=int(j)
    r.append(sum)
print(r)

[5, 7, 11, 13, 5, 8, 11, 15, 17, 1]


### 10.	write a Python program to Break a list into chunks of size N 

In [23]:
import numpy as np
n=5
arr10=[41,52,83,94,5,26,47,78,89,10]
np.array_split(arr10, 6)

[array([41, 52]),
 array([83, 94]),
 array([ 5, 26]),
 array([47, 78]),
 array([89]),
 array([10])]

### 11.	write a Python program to Sort the values of first list using second list

In [27]:
def sort_list(list1, list2):
	zipped_pairs = zip(list2, list1)
	z = [x for _, x in sorted(zipped_pairs)]
	return z
 
x = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
y = [0, 1, 1, 0, 1, 2, 2, 0, 1]

print(sort_list(x, y))

x = ["g", "e", "e", "k", "s", "f", "o", "r", "g", "e", "e", "k", "s"]
y = [0, 1, 1, 0, 1, 2, 2, 0, 1]

print(sort_list(x, y))


['a', 'd', 'h', 'b', 'c', 'e', 'i', 'f', 'g']
['g', 'k', 'r', 'e', 'e', 'g', 's', 'f', 'o']
